### ISSUE TITLE
comma_separated_keywords

### ISSUE THREAD

**Issue by the-jojo-jj** [s101d1/PlayStoreScrapy#2]
Hi, I got this messages, can somebody help me?

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.7/dist-packages/scrapy/cmdline.py", line 144, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 280, in __init__
    super().__init__(settings)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 152, in __init__
    self.spider_loader = self._get_spider_loader(settings)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 146, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spiderloader.py", line 67, in from_settings
    return cls(settings)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spiderloader.py", line 24, in __init__
    self._load_all_spiders()
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spiderloader.py", line 51, in _load_all_spiders
    for module in walk_modules(name):
  File "/usr/local/lib/python3.7/dist-packages/scrapy/utils/misc.py", line 88, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/PlayStoreScrapy/scraper/spiders/spider.py", line 72
    print '\n>>> Command Usage: scrapy crawl playstorescrapy -a keywords=<comma_separated_keywords> [options]'
                                                                                                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('\n>>> Command Usage: scrapy crawl playstorescrapy -a keywords=<comma_separated_keywords> [options]')?

**Comment by s101d1** [comment]
You need python 2. This project doesn't support python 3.

**Comment by the-jojo-jj** [comment]
I do, currently python2.7.16

python --version
Python 2.7.16

**Comment by s101d1** [comment]
In your traceback above:

```
Traceback (most recent call last):
File "/usr/local/bin/scrapy", line 10, in
sys.exit(execute())
File "/usr/local/lib/python3.7/dist-packages/scrapy/cmdline.py", line 144, in execute
cmd.crawler_process = CrawlerProcess(settings)
File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 280, in init
super().init(settings)
File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 152, in init
self.spider_loader = self._get_spider_loader(settings)
File "/usr/local/lib/python3.7/dist-packages/scrapy/crawler.py", line 146, in _get_spider_loader
return loader_cls.from_settings(settings.frozencopy())
File "/usr/local/lib/python3.7/dist-packages/scrapy/spiderloader.py", line 67, in from_settings
return cls(settings)
File "/usr/local/lib/python3.7/dist-packages/scrapy/spiderloader.py", line 24, in init
self._load_all_spiders()
...
```


> File "/usr/local/lib/python3.7/...

You're running python 3 on the project.

Also FYI, this project isn't maintained anymore. The program might not work with the current playstore anymore.
